"""auto-generated migration

Revision ID: 2713f5814688
Revises: ee6e61fa3e7b
Create Date: 2026-02-17 01:18:30.724142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2713f5814688'
down_revision: Union[str, Sequence[str], None] = 'ee6e61fa3e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_persons_person_id'), table_name='case_persons')
    op.drop_index(op.f('ix_cases_status_created_at'), table_name='cases')
    op.drop_index(op.f('ix_incident_tags_tag_id'), table_name='incident_tags')
    op.drop_index(op.f('ix_incidents_district'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_occurred_at'), table_name='incidents')
    op.drop_column('incidents', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_incidents_occurred_at'), 'incidents', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_incidents_district'), 'incidents', ['district'], unique=False)
    op.create_index(op.f('ix_incident_tags_tag_id'), 'incident_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_cases_status_created_at'), 'cases', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_case_persons_person_id'), 'case_persons', ['person_id'], unique=False)
    # ### end Alembic commands ###
