"""auto-generated migration

Revision ID: fef4a6cf3e7c
Revises: f4e7aacbfd9d
Create Date: 2026-02-17 01:22:16.505453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef4a6cf3e7c'
down_revision: Union[str, Sequence[str], None] = 'f4e7aacbfd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
